-- Optional development catalog seed. Run after supabase/schema.sql.
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Premium Basmati Rice (50kg)', 'premium-basmati-rice-50kg', 'High-quality long grain basmati rice, perfect for special occasions', 85000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Brown Beans (10kg)', 'brown-beans-10kg', 'Fresh brown beans, rich in protein and perfect for Nigerian dishes', 12000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1589542840482-c7c456d2e93c?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('White Garri (5kg)', 'white-garri-5kg', 'Premium quality white garri, finely processed and hygienically packaged', 4500.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1625937286074-9ca519d5d9df?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Yellow Garri (5kg)', 'yellow-garri-5kg', 'Traditional yellow garri with authentic taste and aroma', 5000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Vegetable Oil (25 Liters)', 'vegetable-oil-25-liters', 'Pure vegetable cooking oil, ideal for all your cooking needs', 45000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Groundnut Oil (5 Liters)', 'groundnut-oil-5-liters', 'Natural groundnut oil with rich flavor and nutrients', 18000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1608074978583-33080d2c3ebb?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Sugar (50kg)', 'sugar-50kg', 'Refined white sugar for all your sweetening needs', 65000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1584043204475-8cc101d6c77a?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Salt (1kg pack of 10)', 'salt-1kg-pack-of-10', 'Iodized table salt, essential for healthy cooking', 3500.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1607755385930-c68d0f5b85b1?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Luxury Gift Basket', 'luxury-gift-basket', 'Beautifully curated gift basket with premium items', 35000.0, (select id from public.categories where slug = 'gifts'), 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Corporate Gift Hamper', 'corporate-gift-hamper', 'Professional gift hamper perfect for business occasions', 50000.0, (select id from public.categories where slug = 'gifts'), 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Birthday Gift Box', 'birthday-gift-box', 'Colorful gift box filled with treats and surprises', 15000.0, (select id from public.categories where slug = 'gifts'), 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Cleaning Detergent (5kg)', 'cleaning-detergent-5kg', 'Powerful cleaning detergent for all household needs', 8500.0, (select id from public.categories where slug = 'household'), 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Toilet Paper (Pack of 20)', 'toilet-paper-pack-of-20', 'Soft and absorbent toilet tissue, bulk pack', 12000.0, (select id from public.categories where slug = 'household'), 'https://images.unsplash.com/photo-1584556326561-c8746083993b?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Hand Soap (Pack of 12)', 'hand-soap-pack-of-12', 'Antibacterial hand soap bars for daily hygiene', 6000.0, (select id from public.categories where slug = 'household'), 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Kitchen Towels (Pack of 10)', 'kitchen-towels-pack-of-10', 'Absorbent kitchen paper towels for cleaning', 5500.0, (select id from public.categories where slug = 'household'), 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Premium Rice 50kg', 'premium-rice-50kg', 'High quality long grain rice', 45000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Vegetable Oil 5L', 'vegetable-oil-5l', 'Pure vegetable cooking oil', 8500.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Gift Basket Deluxe', 'gift-basket-deluxe', 'Luxury gift basket with assorted items', 15000.0, (select id from public.categories where slug = 'gifts'), 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Cleaning Kit Pro', 'cleaning-kit-pro', 'Complete household cleaning kit', 12000.0, (select id from public.categories where slug = 'household'), 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Pasta 1kg Pack', 'pasta-1kg-pack', 'Premium quality pasta', 2500.0, (select id from public.categories where slug = 'foodstuffs'), 'https://images.unsplash.com/photo-1551462147-37cc0f2da6a3?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('Ceramic Vase Set', 'ceramic-vase-set', 'Beautiful decorative vase set', 18000.0, (select id from public.categories where slug = 'gifts'), 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=400&h=400&fit=crop', 100, true) on conflict (slug) do nothing;
insert into public.products (name, slug, description, price, category_id, image_url, stock_quantity, is_active) values ('hairy', 'hairy', 'hsxnsxis
', 20000.0, (select id from public.categories where slug = 'foodstuffs'), 'https://i.pinimg.com/236x/cd/07/70/cd0770590bda27990acfb16eb161ad8f.jpg', 100, true) on conflict (slug) do nothing;
